name: ghd
author: Steffen Ohrendorf
description: GitHub Deployer
inputs:
  user:
    required: false
    description: Username when creating a new deployment (required to trigger the "deployment" trigger)
    default: ""
  access_token:
    required: true
    description: Access token of the user when creating a new deployment
  args:
    required: true
    description: Args to the action.
outputs:
  deployment_id:
    description: The deployment id when creating a deployment

runs:
  using: docker
  image: docker://moneymeets/ghd:v3
  env:
    GITHUB_USER: ${{ inputs.user }}
    GITHUB_TOKEN: ${{ inputs.access_token }}
  args:
    - ${{ inputs.args }}
