#!/bin/bash

# Link me into your $PATH as `ln -s ../path/to/ghd`

script_path() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        READLINK="readlink"
    else
        READLINK="readlink -f"
    fi

    local resolved="$($READLINK "${BASH_SOURCE[0]}")"
    echo "$(dirname "$resolved")"
}

current_dir="$(pwd -P)"
script_path="$(script_path)"

cd "$script_path"

set +e

unset VIRTUAL_ENV
poetry run bash -c " cd \"$current_dir\" && \"$script_path/ghd.py\" \"\$@\"" -- "$@"
